# FASE 1 · ANÁLISIS EXPLORATORIO DE DATOS (EDA)

En esta primera fase se realiza una exploración inicial del conjunto de datos con el objetivo de comprender su estructura, evaluar su calidad y detectar posibles problemas antes de iniciar la fase de limpieza.

A lo largo del análisis se revisan:
- las dimensiones del dataset,
- los tipos de variables,
- la distribución general de las columnas,
- la presencia de duplicados,
- los valores nulos,
- y los estadísticos descriptivos principales.

Esta fase permite identificar qué transformaciones serán necesarias en la etapa posterior y establecer una base sólida para el análisis.

In [1]:
# Importación de librerías

import pandas as pd
import numpy as np

# Configuración para visualizar todas las columnas del DataFrame
pd.set_option('display.max_columns', None)

In [ ]:
# Carga del dataset

df_hr = pd.read_csv("../files/raw/hr.csv")

# Visualizamos las primeras filas para comprobar que la carga se ha realizado correctamente

df_hr.head()

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EmployeeNumber,EnvironmentSatisfaction,Gender,HourlyRate,JobInvolvement,JobLevel,JobRole,JobSatisfaction,MaritalStatus,MonthlyIncome,MonthlyRate,NumCompaniesWorked,Over18,OverTime,PercentSalaryHike,PerformanceRating,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,41.0,Yes,Travel_Rarely,1102,Sales,1,2,Life Sciences,1,1,2,Female,94,3,2,sALES eXECUTIVE,4.0,Single,5993.0,19479,8,Y,Yes,11,3,1,80.0,0,8,0.0,1,6,4,0,5.0
1,49.0,No,Travel_Frequently,279,Research & Development,8,1,Life Sciences,1,2,3,Male,61,2,2,rESEARCH sCIENTIST,2.0,Married,5130.0,24907,1,Y,No,23,4,4,NaN,1,10,3.0,3,10,7,1,7.0
2,37.0,Yes,Travel_Rarely,1373,Research & Development,2,2,Other,1,4,4,Male,92,2,1,lABORATORY tECHNICIAN,3.0,Single,2090.0,2396,6,Y,Yes,15,3,2,NaN,0,7,3.0,3,0,0,0,0.0
3,33.0,No,Travel_Frequently,1392,Research & Development,3,4,Life Sciences,1,5,4,Female,56,3,1,rESEARCH sCIENTIST,3.0,Married,2909.0,23159,1,Y,Yes,11,3,3,80.0,0,8,3.0,3,8,7,3,0.0
4,27.0,No,Travel_Rarely,591,Research & Development,2,1,Medical,1,7,1,Male,40,3,1,lABORATORY tECHNICIAN,2.0,Married,3468.0,16632,9,Y,No,12,3,4,80.0,1,6,3.0,3,2,2,2,2.0

In [3]:
# Dimensiones del DataFrame

print(f"El DataFrame tiene {df_hr.shape[0]} filas y {df_hr.shape[1]} columnas.\n")

El DataFrame tiene 1474 filas y 35 columnas.

In [4]:
# Identificación de columnas por tipo de dato

df_categoricas = df_hr.select_dtypes(include='str')
df_numericas = df_hr.select_dtypes(exclude='str')

print(f"Variables Categóricas: {df_categoricas.columns.tolist()}")
print(f"Variables Numéricas: {df_numericas.columns.tolist()}")

Variables Categóricas: ['Attrition', 'BusinessTravel', 'Department', 'EducationField', 'Gender', 'JobRole', 'MaritalStatus', 'Over18', 'OverTime']
Variables Numéricas: ['Age', 'DailyRate', 'DistanceFromHome', 'Education', 'EmployeeCount', 'EmployeeNumber', 'EnvironmentSatisfaction', 'HourlyRate', 'JobInvolvement', 'JobLevel', 'JobSatisfaction', 'MonthlyIncome', 'MonthlyRate', 'NumCompaniesWorked', 'PercentSalaryHike', 'PerformanceRating', 'RelationshipSatisfaction', 'StandardHours', 'StockOptionLevel', 'TotalWorkingYears', 'TrainingTimesLastYear', 'WorkLifeBalance', 'YearsAtCompany', 'YearsInCurrentRole', 'YearsSinceLastPromotion', 'YearsWithCurrManager']

## Exploración general de las variables

A continuación, se revisa cada columna para conocer su tipo de dato, porcentaje de valores nulos y número de valores únicos.  
En el caso de las variables categóricas, también se muestra una muestra de sus categorías para facilitar su interpretación.

In [5]:
# Revisión general por columna

print("ANÁLISIS POR COLUMNA\n")

for columna in df_hr.columns:
    print("Columna: ", columna)
    print("Tipo de dato: ", df_hr[columna].dtype)
    print(f"Porcentaje de nulos: {round(df_hr[columna].isnull().mean() * 100, 2)}%")
    print("Valores únicos: ", df_hr[columna].unique())
    print("Número de valores únicos: ", df_hr[columna].nunique())
    print("----------------------\n")

ANÁLISIS POR COLUMNA

Columna:  Age
Tipo de dato:  float64
Porcentaje de nulos: 4.95%
Valores únicos:  [41. 49. 37. 33. 27. 32. 59. 30. 38. 36. 35. 29. 31. 34. 28. 22. 53. 24.
 21. 42. 44. 46. 39. 43. 50. 26. 48. nan 55. 45. 56. 23. 51. 40. 54. 58.
 20. 25. 19. 57. 52. 47. 18. 60.]
Número de valores únicos:  43
----------------------

Columna:  Attrition
Tipo de dato:  str
Porcentaje de nulos: 0.0%
Valores únicos:  <StringArray>
['Yes', 'No']
Length: 2, dtype: str
Número de valores únicos:  2
----------------------

Columna:  BusinessTravel
Tipo de dato:  str
Porcentaje de nulos: 7.94%
Valores únicos:  <StringArray>
['Travel_Rarely', 'Travel_Frequently', 'Non-Travel', nan]
Length: 4, dtype: str
Número de valores únicos:  3
----------------------

Columna:  DailyRate
Tipo de dato:  int64
Porcentaje de nulos: 0.0%
Valores únicos:  [1102  279 1373 1392  591 1005 1324 1358  216 1299  809  153  670 1346
  103 1389  334 1123 1219  371  673 1218  419  391  699 1282 1125  691
  477  705  924 1459  125  895  813 1273  869  890  852 1141  464 1240
 1357  994  721 1360 1065  408 1211 1229  626 1434 1488 1097 1443  515
  853 1142  655 1115  427  653  989 1435 1223  836 1195 1339  664  318
 1225 1328 1082  548  132  746  776  193  397  945 1214  111  573 1153
 1400  541  432  288  669  530  632 1334  638 1093 1217 1353  120  682
  489  807  827  871  665 1040 1420  240 1280  534 1456  658  142 1127
 1031 1189 1354 1467  922  394 1312  750  441  684  249  841  147  528
  594  470  957  542  802 1355 1150 1329  959 1033 1316  364  438  689
  201 1427  857  933 1181 1395  662 1436  194  967 1496 1169 1145  630
  303 1256  440 1450 1452  465  702 1157  602 1480 1268  713  134  526
 1380  140  629 1356  328 1084  931  692 1069  313  894  556 1344  290
  138  926 1261  472 1002  878  905 1180  121 1136  635 1151  644 1045
  829 1242 1469  896  992 1052 1147 1396  663  119  979  319 1413  944
 1323  532  818  854 1034  771 1401 1431  976 1411 1300  252 1327  832
 1017 1199  504  505  916 1247  685  269 1416  833  307 1311  128  488
  529 1210 1463  675 1385 1403  452  666 1158  228  996  728 1315  322
 1479  797 1070  442  496 1372  920  688 1449 1117  636  506  444  950
  889  555  230 1232  566 1302  812 1476  218 1132 1105  906  849  390
  106 1249  192  553  117  185 1091  723 1220  588 1377 1018 1275  798
  672 1162  508 1482  559  210  928 1001  549 1124  738  570 1130 1192
  343  144 1296 1309  483  810  544 1062 1319  641 1332  756  845  593
 1171  350  921 1144  143 1046  575  156 1283  755  304 1178  329 1362
 1371  202  253  164 1107  759 1305  982  821 1381  480 1473  891 1063
  645 1490  317  422 1485 1368 1448  296 1398 1349  986 1099 1116 1499
  983 1009 1303 1274 1277  587  413 1276  988 1474  163  267  619  302
  443  828  561  426  232 1306 1094  509  775  195  258  471  799  956
  535 1495  446 1245  703  823 1246  622 1287  448  254 1365  538  525
  558  782  362 1236 1112  204 1343  604 1216  646  160  238 1397  306
  991  482 1176  913 1076  727  885  243  806  817 1410 1207 1442  693
  929  562  608  580  970 1179  294  314  316  654  168  381  217  501
  650  141  804  975 1090  346  430  268  167  621  527  883  954  310
  719  725  715  657 1146  182  376  571  384  791 1111 1243 1092 1325
  805  213  118  676 1252  286 1258  932 1041  859  720  946 1184  436
  589  760  887 1318  625  180  586 1012  661  930  342 1230 1271 1278
  607  130  300  583 1418 1269  379  395 1265 1222  341  868 1231  102
  881 1383 1075  374 1086  781  177  500 1425 1454  617 1085  995 1122
  618  546  462 1198 1272  154 1137 1188  188 1333  867  263  938  129
  616  498 1404 1053  289 1376  231  152  882  903 1379  335  722  461
  974 1126  840 1134  248  955  939 1391 1206  287 1441  109 1066  277
  466 1055  265  135  247 1035  266  145 1038 1234 1109 1089  788  124
  660 1186 1464  796  415  769 1003 1366  330 1492 1204  309 1330  469
  697 1262 1050  770  406  203 1308  984  439  793 1451 1182  174  490
  718  433  773  603  874  367  199  481  647 1384  902  819  862 1457
  977  942 1402 1421 1361  917  200  150  179  696  116  363  107 1465
  458 1212 1103  966 1010  326 1098  969 1167  694 1320  536  373  599
  251  131  237 1429  648  735  531  429  968  879  640  412  848  360
 1138  325 1322  299 1030  634  524  256 1060  935  495  282  206  943
  523  507  601  855 1291 1405 1369  999 1202  285  404  736 1498 1200
 1439  499  205  683 1462  949  652  332 1475  337  971 1174  667  560
  172  383 1255  359  401  377  592 1445 1221  866  981  447 1326  748
  990  405  115  790  830 1193 1423  467  271  410 1083  516  224  136
 1029  333 1440  674 1342  898  824  492  598  740  888 1288  104 1108
  479 1351  474  437  884 1370  264 1059  563  457 1313  241 1015  336
 1387  170  208  671  711  737 1470  365  763  567  486  772  301  311
  584  880  392  148  708 1259  786  370  678  146  581  918 1238  585
  741  552  369  717  543  964  792  611  176  897  600 1054  428  181
  211 1079  590  305  953  478 1375  244  511 1294  196  734 1239 1253
 1128 1336  234  766  261 1194  431  572 1422 1297  574  355  207  706
  280  726  414  352 1224  459 1254 1131  835 1172 1266  783  219 1213
 1096 1251 1394  605 1064 1337  937  157  754 1168  155 1444  189  911
 1321 1154  557  642  801  161 1382 1037  105  582  704  345 1120 1378
  468  613 1023  628]
Número de valores únicos:  886
----------------------

Columna:  Department
Tipo de dato:  str
Porcentaje de nulos: 1.97%
Valores únicos:  <StringArray>
['Sales', 'Research & Development', nan, 'Human Resources']
Length: 4, dtype: str
Número de valores únicos:  3
----------------------

Columna:  DistanceFromHome
Tipo de dato:  int64
Porcentaje de nulos: 0.0%
Valores únicos:  [ 1  8  2  3 24 23 27 16 15 26 19 21  5 11  9  7  6 10  4 25 12 18 29 22
 14 20 28 17 13]
Número de valores únicos:  29
----------------------

Columna:  Education
Tipo de dato:  int64
Porcentaje de nulos: 0.0%
Valores únicos:  [2 1 4 3 5]
Número de valores únicos:  5
----------------------

Columna:  EducationField
Tipo de dato:  str
Porcentaje de nulos: 3.93%
Valores únicos:  <StringArray>
[   'Life Sciences',            'Other',          'Medical',
                nan,        'Marketing', 'Technical Degree',
  'Human Resources']
Length: 7, dtype: str
Número de valores únicos:  6
----------------------

Columna:  EmployeeCount
Tipo de dato:  int64
Porcentaje de nulos: 0.0%
Valores únicos:  [1]
Número de valores únicos:  1
----------------------

Columna:  EmployeeNumber
Tipo de dato:  int64
Porcentaje de nulos: 0.0%
Valores únicos:  [   1    2    4 ... 2064 2065 2068]
Número de valores únicos:  1470
----------------------

Columna:  EnvironmentSatisfaction
Tipo de dato:  int64
Porcentaje de nulos: 0.0%
Valores únicos:  [2 3 4 1]
Número de valores únicos:  4
----------------------

Columna:  Gender
Tipo de dato:  str
Porcentaje de nulos: 0.0%
Valores únicos:  <StringArray>
['Female', 'Male']
Length: 2, dtype: str
Número de valores únicos:  2
----------------------

Columna:  HourlyRate
Tipo de dato:  int64
Porcentaje de nulos: 0.0%
Valores únicos:  [ 94  61  92  56  40  79  81  67  44  84  49  31  93  50  51  80  96  78
  45  82  53  83  58  72  48  42  41  86  97  75  33  37  73  98  36  47
  71  30  43  99  59  95  57  76  87  66  55  32  52  70  62  64  63  60
 100  46  39  77  35  91  54  34  90  65  88  85  89  68  69  74  38]
Número de valores únicos:  71
----------------------

Columna:  JobInvolvement
Tipo de dato:  int64
Porcentaje de nulos: 0.0%
Valores únicos:  [3 2 4 1]
Número de valores únicos:  4
----------------------

Columna:  JobLevel
Tipo de dato:  int64
Porcentaje de nulos: 0.0%
Valores únicos:  [2 1 3 4 5]
Número de valores únicos:  5
----------------------

Columna:  JobRole
Tipo de dato:  str
Porcentaje de nulos: 0.0%
Valores únicos:  <StringArray>
[          ' sALES eXECUTIVE ',        ' rESEARCH sCIENTIST ',
     ' lABORATORY tECHNICIAN ',    ' mANUFACTURING dIRECTOR ',
 ' hEALTHCARE rEPRESENTATIVE ',                   ' mANAGER ',
      ' sALES rEPRESENTATIVE ',         ' rESEARCH dIRECTOR ',
           ' hUMAN rESOURCES ']
Length: 9, dtype: str
Número de valores únicos:  9
----------------------

Columna:  JobSatisfaction
Tipo de dato:  float64
Porcentaje de nulos: 1.97%
Valores únicos:  [ 4.  2.  3.  1. nan]
Número de valores únicos:  4
----------------------

Columna:  MaritalStatus
Tipo de dato:  str
Porcentaje de nulos: 8.96%
Valores únicos:  <StringArray>
['Single', 'Married', 'Divorced', nan, 'Marreid']
Length: 5, dtype: str
Número de valores únicos:  4
----------------------

Columna:  MonthlyIncome
Tipo de dato:  float64
Porcentaje de nulos: 0.95%
Valores únicos:  [5993. 5130. 2090. ... 9991. 5390. 4404.]
Número de valores únicos:  1336
----------------------

Columna:  MonthlyRate
Tipo de dato:  int64
Porcentaje de nulos: 0.0%
Valores únicos:  [19479 24907  2396 ...  5174 13243 10228]
Número de valores únicos:  1427
----------------------

Columna:  NumCompaniesWorked
Tipo de dato:  int64
Porcentaje de nulos: 0.0%
Valores únicos:  [8 1 6 9 0 4 5 2 7 3]
Número de valores únicos:  10
----------------------

Columna:  Over18
Tipo de dato:  str
Porcentaje de nulos: 0.0%
Valores únicos:  <StringArray>
['Y']
Length: 1, dtype: str
Número de valores únicos:  1
----------------------

Columna:  OverTime
Tipo de dato:  str
Porcentaje de nulos: 2.99%
Valores únicos:  <StringArray>
['Yes', 'No', nan]
Length: 3, dtype: str
Número de valores únicos:  2
----------------------

Columna:  PercentSalaryHike
Tipo de dato:  int64
Porcentaje de nulos: 0.0%
Valores únicos:  [11 23 15 12 13 20 22 21 17 14 16 18 19 24 25]
Número de valores únicos:  15
----------------------

Columna:  PerformanceRating
Tipo de dato:  int64
Porcentaje de nulos: 0.0%
Valores únicos:  [3 4]
Número de valores únicos:  2
----------------------

Columna:  RelationshipSatisfaction
Tipo de dato:  int64
Porcentaje de nulos: 0.0%
Valores únicos:  [1 4 2 3]
Número de valores únicos:  4
----------------------

Columna:  StandardHours
Tipo de dato:  float64
Porcentaje de nulos: 11.13%
Valores únicos:  [80. nan]
Número de valores únicos:  1
----------------------

Columna:  StockOptionLevel
Tipo de dato:  int64
Porcentaje de nulos: 0.0%
Valores únicos:  [0 1 3 2]
Número de valores únicos:  4
----------------------

Columna:  TotalWorkingYears
Tipo de dato:  int64
Porcentaje de nulos: 0.0%
Valores únicos:  [ 8 10  7  6 12  1 17  5  3 31 13  0 26 24 22  9 19  2 23 14 15  4 29 28
 21 25 20 11 16 37 38 30 40 18 36 34 32 33 35 27]
Número de valores únicos:  40
----------------------

Columna:  TrainingTimesLastYear
Tipo de dato:  float64
Porcentaje de nulos: 5.97%
Valores únicos:  [ 0.  3.  2.  5.  1.  4. nan  6.]
Número de valores únicos:  7
----------------------

Columna:  WorkLifeBalance
Tipo de dato:  int64
Porcentaje de nulos: 0.0%
Valores únicos:  [1 3 2 4]
Número de valores únicos:  4
----------------------

Columna:  YearsAtCompany
Tipo de dato:  int64
Porcentaje de nulos: 0.0%
Valores únicos:  [ 6 10  0  8  2  7  1  9  5  4 25  3 12 14 22 15 27 21 17 11 13 37 16 20
 40 24 33 19 36 18 29 31 32 34 26 30 23]
Número de valores únicos:  37
----------------------

Columna:  YearsInCurrentRole
Tipo de dato:  int64
Porcentaje de nulos: 0.0%
Valores únicos:  [ 4  7  0  2  5  9  8  3  6 13  1 15 14 16 11 10 12 18 17]
Número de valores únicos:  19
----------------------

Columna:  YearsSinceLastPromotion
Tipo de dato:  int64
Porcentaje de nulos: 0.0%
Valores únicos:  [ 0  1  3  2  7  4  8  6  5 15  9 13 12 10 11 14]
Número de valores únicos:  16
----------------------

Columna:  YearsWithCurrManager
Tipo de dato:  float64
Porcentaje de nulos: 10.04%
Valores únicos:  [ 5.  7.  0.  2.  6. nan  8.  3. 11. 17.  4.  1. 12.  9. 10. 15. 13. 16.
 14.]
Número de valores únicos:  18
----------------------

In [6]:
# Revisión de variables constantes o con una única categoría

columnas_constantes = ["Over18", "EmployeeCount", "StandardHours"]

for col in columnas_constantes:
    print(f"{col}: {df_hr[col].unique()}")

Over18: <StringArray>
['Y']
Length: 1, dtype: str
EmployeeCount: [1]
StandardHours: [80. nan]

In [7]:
# Identificación de filas duplicadas

print(f"El DataFrame contiene {df_hr.duplicated().sum()} filas duplicadas.")
df_hr[df_hr.duplicated()]

El DataFrame contiene 4 filas duplicadas.

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EmployeeNumber,EnvironmentSatisfaction,Gender,HourlyRate,JobInvolvement,JobLevel,JobRole,JobSatisfaction,MaritalStatus,MonthlyIncome,MonthlyRate,NumCompaniesWorked,Over18,OverTime,PercentSalaryHike,PerformanceRating,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
1470,28.0,No,Travel_Rarely,866,Sales,5,3,Medical,1,1469,4,Male,84,3,2,sALES eXECUTIVE,1.0,Single,8463.0,23490,0,Y,No,18,3,4,NaN,0,6,4.0,3,5,4,1,NaN
1471,53.0,No,Travel_Rarely,1084,Research & Development,13,2,Medical,1,250,4,Female,57,4,2,mANUFACTURING dIRECTOR,1.0,Divorced,4450.0,26250,1,Y,No,11,3,3,NaN,2,5,3.0,3,4,2,1,3.0
1472,24.0,Yes,Travel_Rarely,240,Human Resources,22,1,Human Resources,1,1714,4,Male,58,1,1,hUMAN rESOURCES,3.0,Married,1555.0,11585,1,Y,No,11,3,3,80.0,1,1,2.0,3,1,0,0,0.0
1473,45.0,No,Travel_Rarely,1339,Research & Development,7,3,Life Sciences,1,86,2,Male,59,3,3,rESEARCH sCIENTIST,1.0,Divorced,9724.0,18787,2,Y,No,17,3,3,NaN,1,25,2.0,3,1,0,0,0.0

In [8]:
# Estadísticos descriptivos de las variables numéricas

df_hr.describe().T

,count,mean,std,min,25%,50%,75%,max
Age,1401.0,36.944325,9.105009,18.0,30.00,36.0,43.00,60.0
DailyRate,1474.0,802.702171,403.539530,102.0,465.00,803.0,1157.00,1499.0
DistanceFromHome,1474.0,9.199457,8.104266,1.0,2.00,7.0,14.00,29.0
Education,1474.0,2.911126,1.024267,1.0,2.00,3.0,4.00,5.0
EmployeeCount,1474.0,1.000000,0.000000,1.0,1.00,1.0,1.00,1.0
EmployeeNumber,1474.0,1024.471506,602.421193,1.0,488.75,1020.5,1555.75,2068.0
EnvironmentSatisfaction,1474.0,2.723881,1.093280,1.0,2.00,3.0,4.00,4.0
HourlyRate,1474.0,65.887381,20.310444,30.0,48.00,66.0,83.75,100.0
JobInvolvement,1474.0,2.729986,0.712861,1.0,2.00,3.0,3.00,4.0
JobLevel,1474.0,2.063772,1.106055,1.0,1.00,2.0,3.00,5.0
JobSatisfaction,1445.0,2.728720,1.106409,1.0,2.00,3.0,4.00,4.0
MonthlyIncome,1460.0,6497.448630,4706.059294,1009.0,2909.00,4907.0,8377.00,19999.0
MonthlyRate,1474.0,14328.611940,7120.225285,2094.0,8054.50,14248.5,20465.75,26999.0
NumCompaniesWorked,1474.0,2.688602,2.496443,0.0,1.00,2.0,4.00,9.0
PercentSalaryHike,1474.0,15.206920,3.659274,11.0,12.00,14.0,18.00,25.0
PerformanceRating,1474.0,3.153324,0.360422,3.0,3.00,3.0,3.00,4.0
RelationshipSatisfaction,1474.0,2.713704,1.080338,1.0,2.00,3.0,4.00,4.0
StandardHours,1310.0,80.000000,0.000000,80.0,80.00,80.0,80.00,80.0
StockOptionLevel,1474.0,0.794437,0.851784,0.0,0.00,1.0,1.00,3.0
TotalWorkingYears,1474.0,11.274084,7.785972,0.0,6.00,10.0,15.00,40.0
TrainingTimesLastYear,1386.0,2.797980,1.296882,0.0,2.00,3.0,3.00,6.0
WorkLifeBalance,1474.0,2.761872,0.705625,1.0,2.00,3.0,3.00,4.0
YearsAtCompany,1474.0,6.996608,6.122920,0.0,3.00,5.0,9.00,40.0
YearsInCurrentRole,1474.0,4.221845,3.622032,0.0,2.00,3.0,7.00,18.0
YearsSinceLastPromotion,1474.0,2.183175,3.219356,0.0,0.00,1.0,3.00,15.0
YearsWithCurrManager,1326.0,4.061840,3.517603,0.0,2.00,3.0,7.00,17.0

In [9]:
# Estadísticos descriptivos de las variables categóricas

df_hr.describe(include="str").T

               count unique                     top  freq
Attrition       1474      2                      No  1236
BusinessTravel  1357      3           Travel_Rarely   955
Department      1445      3  Research & Development   941
EducationField  1416      6           Life Sciences   582
Gender          1474      2                    Male   885
JobRole         1474      9        sALES eXECUTIVE    327
MaritalStatus   1342      4                 Married   604
Over18          1474      1                       Y  1474
OverTime        1430      2                      No  1025

In [10]:
# Resumen de valores nulos por columna

porcentaje_nulos = round((df_hr.isnull().sum() / df_hr.shape[0]) * 100, 2)
porcentaje_nulos[porcentaje_nulos > 0].sort_values(ascending=False)

StandardHours            11.13
YearsWithCurrManager     10.04
MaritalStatus             8.96
BusinessTravel            7.94
TrainingTimesLastYear     5.97
Age                       4.95
EducationField            3.93
OverTime                  2.99
Department                1.97
JobSatisfaction           1.97
MonthlyIncome             0.95
dtype: float64

In [ ]:
# Listado de Job Roles por Department
df_hr[['Department', 'JobRole']].drop_duplicates().sort_values(by='Department')

                 Department                      JobRole
79          Human Resources             hUMAN rESOURCES
105         Human Resources                     mANAGER
1    Research & Development          rESEARCH sCIENTIST
2    Research & Development       lABORATORY tECHNICIAN
8    Research & Development      mANUFACTURING dIRECTOR
9    Research & Development   hEALTHCARE rEPRESENTATIVE
22   Research & Development           rESEARCH dIRECTOR
25   Research & Development                     mANAGER
0                     Sales             sALES eXECUTIVE
18                    Sales                     mANAGER
21                    Sales        sALES rEPRESENTATIVE
7                       NaN       lABORATORY tECHNICIAN
46                      NaN             sALES eXECUTIVE
65                      NaN                     mANAGER
222                     NaN           rESEARCH dIRECTOR
410                     NaN      mANUFACTURING dIRECTOR
547                     NaN          rESEARCH sCIENTIST
735                     NaN   hEALTHCARE rEPRESENTATIVE

Este análisis exploratorio permite revisar la correspondencia entre departamento y puesto.
A partir de este resultado se detecta que algunos valores de JobRole, como "Manager", aparecen en varios departamentos distintos. Esto puede generar ambigüedad en la interpretación de la categoría, ya que el nombre del puesto no recoge suficiente contexto.
Por ello, en la fase de transformación se planteará enriquecer esta variable incorporando el departamento en aquellos casos necesarios para mejorar su claridad y trazabilidad analítica.

### Conclusión

El análisis exploratorio ha permitido identificar las principales características del dataset, así como detectar posibles problemas de calidad de los datos.

Se han observado valores nulos en determinadas variables, inconsistencias en formatos y la necesidad de transformar algunas columnas para facilitar su análisis. Además, se han identificado variables potencialmente relevantes para el estudio del attrition, como el nivel del puesto, el salario, el equilibrio vida-trabajo y la carga laboral.

Este análisis inicial sienta las bases para la siguiente fase, en la que se realizará la limpieza y transformación del dataset con el fin de preparar los datos para un análisis más profundo.